### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by KimoriWasTaken** [UncleGoogle/galaxy-integration-osu#11]
Worked at first when I installed it, but after a day or a restart of my pc pretty much I can't seem to be able to connect my account again.
It just says "Connection Lost" in red.
Tried deleting and reinstalling the plugin but it looks like my credentials or something are saved somewhere because it doesn't even open a browser window anymore when I try to connect.
Also tried compiling the latest version myself but I'm getting some weird psutil errors which is a whole other issue...

**Comment by UncleGoogle** [comment]
Hey. Please attach plugin logs from `D:\ProgramData\GOG.com\Galaxy\logs\plugin-egg-79764115-b455-4ff0-be13-a316c7c53dec.log` and also  `D:\ProgramData\GOG.com\Galaxy\logs\GalaxyClient.log`  and `D:\ProgramData\GOG.com\Galaxy\logs\GalaxyClient.log1`

**Comment by UncleGoogle** [comment]
create issue about compilation problems if you want. For now my guess is that it comes form the fact that Galaxy uses python32bit and you probably try to build using 64bit python

**Comment by UncleGoogle** [comment]
I forgot to refresh my auth server app. PtyhonAnywhere free plan requires manual reactivation every 3 months. My apologies.

Should work now

**Comment by HonkyToasty** [comment]
its broken again D:

**Comment by UncleGoogle** [comment]
reactivated...
