### ISSUE TITLE
Server leads to dead link on osu site.

### ISSUE THREAD

**Issue by bw8686** [UncleGoogle/galaxy-integration-osu#14]
![GalaxyClient_bzJmfV3WVX](https://user-images.githubusercontent.com/51877146/164243523-a13af892-bc15-4210-ae26-0d5cf6270e39.png)

**Comment by UncleGoogle** [comment]
Ou, probably something has changed on osu API side.
I'll take a look this week.

Meanwhile you can check sources / propose a PR here: https://github.com/UncleGoogle/galaxy-integration-osu-auth

**Comment by UncleGoogle** [comment]
I can't reproduce. Could you please recheck and send me logs from `D:\ProgramData\GOG.com\Galaxy\logs\plugin-egg-79764115-b455-4ff0-be13-a316c7c53dec.log` ?
