### ISSUE TITLE
Wrong osu! guid in registry path

### ISSUE THREAD

**Issue by MrDandycorn** [UncleGoogle/galaxy-integration-osu#3]
Guid in registry path is hardcoded which is probably not supposed to be so. When first installing the integration, it didn't find osu!.exe because of that.

I never used winreg and therefore don't know if this is an optimal solution, but iterating through all subkeys in "SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall" and checking if any of them have "osu!.exe" in DisplayIcon kind of works.

**Comment by UncleGoogle** [comment]
@MrDandycorn You are absolutely right. I hadn't realized that guids are generated by Windows installers. Winreg is jast database so it iterating over all installed items should be fast enough.

**Comment by UncleGoogle** [comment]
@MrDandycorn can you check if PR above works for you?
I wonder if osu can be installed differently than in HKEY_CURRENT_USER

**Comment by MrDandycorn** [comment]
Sorry for the delay
It does indeed work for me

**Comment by UncleGoogle** [comment]
sweet, merging
