### ISSUE TITLE
v1.0.1 "Plugin has crashed"

### ISSUE THREAD

**Issue by rauscheb** [UncleGoogle/galaxy-integration-osu#6]
Did a fresh install of the new published v1.0.1 and the plugin is crashing.

`ImportError: cannot import name '_psutil_windows' from 'psutil' (C:\Users\ethan\AppData\Local\GOG.com\Galaxy\plugins\installed\egg_79764115-b455-4ff0-be13-a316c7c53dec\modules\psutil\__init__.py)`

Log: [plugin-egg-79764115-b455-4ff0-be13-a316c7c53dec.log](https://github.com/UncleGoogle/galaxy-integration-osu/files/4927329/plugin-egg-79764115-b455-4ff0-be13-a316c7c53dec.log)

**Comment by UncleGoogle** [comment]
Thanks for report. It is definitely something wrong with my latest Python3.8 as have the same error for humble bundle last time. Will fix asap

**Comment by UncleGoogle** [comment]
Should work now. Please try it out
