### ISSUE TITLE
Slashbunny's "GOG Galaxy Plugins Downloader" grabbing v1.0.0 instead of latest version

### ISSUE THREAD

**Issue by rauscheb** [UncleGoogle/galaxy-integration-osu#7]
I use [Slashbunny's GOG Galaxy Plugins Downloader](https://github.com/Slashbunny/gog-galaxy-plugin-downloader) to update plugins now and then, and it keeps grabbing v1.0.0 of your plugin instead of the latest.

I haven't dived into how it grabs the latest version, but I thought I'd point it out since I've already bugged you twice now.

**Comment by UncleGoogle** [comment]
Version is hardcoded
https://github.com/Slashbunny/gog-galaxy-plugin-downloader/blob/master/plugins.yaml#L89

Probably could be enhanced by using github API to check releases instead.

**Comment by UncleGoogle** [comment]
already 1.0.1 there
