### ISSUE TITLE
Python Anywhere Error

### ISSUE THREAD

**Issue by otowm** [UncleGoogle/galaxy-integration-osu#8]
Coming Soon!
This is going to be another great website hosted by PythonAnywhere.

this message appear when a try to login to my account

**Comment by Argih** [comment]
It started after the last downtime of the bancho services
https://twitter.com/osustatus/status/1353162176849035265

That made the integration to logout and after it returned started showing that, i will try asking peppy if maybe is something on his side

Edit: that page is actually https://unclegoogle.pythonanywhere.com and is hardcoded in the plugin

**Comment by UncleGoogle** [comment]
Thanks for letting me know. The page is hosted for free on pythonanywhere.com and I need to reactivate it manually every few months. Forgot this time. 

Try now.

**Comment by Argih** [comment]
Is working again for me
