### ISSUE TITLE
Support for lazer

### ISSUE THREAD

**Issue by Wiesmak** [UncleGoogle/galaxy-integration-osu#9]
Add support for lazer

**Comment by UncleGoogle** [comment]
What do you mean @TheWiesmin?

Isn't the official installer from https://osu.ppy.sh/home/download an osu!lazer version?

**Comment by Wiesmak** [comment]
nope

**Comment by Wiesmak** [comment]
it's the stable, would be nice to have lazer option

**Comment by UncleGoogle** [comment]
@TheWiesmin give me official link to lazer installer, so I can take a look

**Comment by Wiesmak** [comment]
It's on [github](https://github.com/ppy/osu/releases/latest/download/install.exe). Also, happy new year 🎉

**Comment by UncleGoogle** [comment]
Thanks, definitely I have to take a look into installation paths and details. Happy new year :tada:

**Comment by UncleGoogle** [comment]
@TheWiesmin 
I don't have windows 8 or bigger so not sure if this works, but please try out the zip from link above.

**Comment by UncleGoogle** [comment]
I've post an update. Tested on my machine this time

**Comment by UncleGoogle** [comment]
Change was released. 
Does it work for you @TheWiesmin ? I checked everything I could except actually running osu!lazer due to OS limitations.

**Comment by Wiesmak** [comment]
@UncleGoogle yeah, now working, thanks
